sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
   - npm install -g coveralls
   - ./scripts/start-server.sh
script:
   - make ci
after_script:
   - ./scripts/stop-server.sh
branches:
  only:
   - master
after_success:
   - rpm run coverage
   - cat ./coverage/lcov.info | coveralls
notifications:
  irc: "irc.freenode.org#brass-monkey"